### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [19, 3, 224, 224] at entry 0 and [18, 3, 224, 224] at entry 8

### ISSUE THREAD

**Issue by yugaljain1999** [swathikirans/violence-recognition-pytorch#13]
@swathikirans I am getting this error while training.. 
Can you please suggest me what should I do in data directories to resolve this error?
Please help me in this..

Error - 
`Traceback (most recent call last):
  File "main-run-vr.py", line 220, in <module>
    __main__()
  File "main-run-vr.py", line 218, in __main__
    noFightsDir_train, fightsDir_test, noFightsDir_test)
  File "main-run-vr.py", line 122, in main_run
    for i, (inputs, targets) in enumerate(trainLoader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [19, 3, 224, 224] at entry 0 and [18, 3, 224, 224] at entry 8

`

Thanks

**Comment by swathikirans** [comment]
The error shows that not all videos contain a minimum of 20 frames. Either update the sequence length to an appropriate value or update the dataloader to take into consideration the cases when the number of frames is less than the sequence length.

**Comment by Sanbot-okk** [comment]
> The error shows that not all videos contain a minimum of 20 frames. Either update the sequence length to an appropriate value or update the dataloader to take into consideration the cases when the number of frames is less than the sequence length.

How should one go about to "update the dataloader to take into consideration the cases when the number of frames is less than the sequence length." ?
