### ISSUE TITLE
when i run :python main-run-vr.py,it has something wrong 

### ISSUE THREAD

**Issue by zhaowuyao** [swathikirans/violence-recognition-pytorch#3]
python main-run-vr.py 
Traceback (most recent call last):
  File "main-run-vr.py", line 219, in <module>
    __main__()
  File "main-run-vr.py", line 217, in __main__
    noFightsDir_train, fightsDir_test, noFightsDir_test)
  File "main-run-vr.py", line 54, in main_run
    shuffle=True, num_workers=numWorkers, pin_memory=True, drop_last=True)
  File "/home/zhaowuyao/disk_a/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/zhaowuyao/disk_a/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

**Comment by swathikirans** [comment]
Please verify if the video frames are placed in the exact same manner as instructed in the readme file.
